In [37]:
#Here we will cover the following:
#1. Comparison Operators
#2. Control Flow
#3. Filtering Data Frames
#4. Loops
#5. Random Numbers
#6. Valueing a call option using simulation

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
os.chdir('../Computational Finance')
os.getcwd()

'/Users/aruvins/Desktop/Fordham/Fall 2025/Computational Finance'

In [39]:
#1. Comparison Operators

In [40]:
2 > 3

False

In [41]:
2>1

True

In [42]:
# The results are boolyan True, or False . Booleans are another 
# Pyton object that take values True or False
#Comparison operators
#>= Greater or equal
#== equal
#!= not-equal


In [43]:
"Carl" < 'Chris'
#Ca is ahead of Ch in the alphabate

True

In [44]:
#But-1...
3 <'Chris'

TypeError: '<' not supported between instances of 'int' and 'str'

In [ ]:
#But-2
'3' < 'Chris'
#Number strings are less than alphabetacal strings

True

In [ ]:
#ou can compare float to integer
3 < 4.1

True

In [ ]:
#comparing an Array to a single value
a = np.array([3,5,7, 12])
print(a)
a>4

[ 3  5  7 12]


array([False,  True,  True,  True])

In [ ]:
#Some Boolean Math
#1. and
#True and True ---> True True and False ---> False False and True ---> False False and False ---> False

#2. or
#True and True ---> True True and False ---> True False and True ---> True False and False ---> False

#3. not is a negation operator



In [ ]:
(not 3) > 3

False

In [ ]:
3 != 3

False

In [ ]:
2!=3

True

In [ ]:
x= 5
x > 3 and x < 4

False

In [ ]:
#with arrays

In [ ]:
a < 8

array([ True,  True,  True, False])

In [ ]:
#Here is an ambiguous condition

In [ ]:
a > 2 and a < 8

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
#To do element-wise comparison we ned
np.logical_and(a > 2 ,a <8)


array([ True,  True,  True, False])

In [ ]:
np.logical_or(a < 5 , a > 7)

array([ True, False, False,  True])

In [ ]:
#2. Control Flow
# The % symbol in Python is called the Modulus Operator (or simply MOD). 
# It returns the remainder of dividing the left hand operand by right hand operand. 
# It's used to get the remainder of a division problem.

In [ ]:
print( 10%3, 11%3 , 12%3)

1 2 0


In [ ]:
z= 12
if z%3 == 0:
    print('z divides by 3')

z divides by 3


In [ ]:
z=8
if z% 2 == 0:
    print('z is even')
else:
    print('z is odd')

z is even


In [ ]:
#3. Filtering DataFrames
#Consider the DataFrame frim previous clas

In [ ]:

sectors= pd.read_csv('dataFiles/sector_weights_returns.csv', index_col=1) 
sectors

sector  recent_weight  1Y_return  3Y_return  \
etf_ticker                                                                     
XLK         S&P Information Technology          0.2422      34.83      42.63   
XLY         S&P Consumer Discretionary          0.0632      27.93      28.65   
XLV                     S&P Healthcare          0.1309      25.59      19.69   
SPY                 US Large Cap Blend          1.0000      28.74      25.99   
XLF                     S&P Financials          0.1423      34.82      20.46   
XLI                    S&P Industrials          0.0886      21.09      20.15   
XLB                      S&P Materials          0.0227      27.45      24.00   
XLRE                   S&P Real Estate          0.0257      45.26      22.31   
XLP               S&P Consumer Staples          0.1200      17.20      18.05   
XLC         S&P Communication Services          0.1114      15.96      24.47   
XLU                      S&P Utilities          0.0245      16.81      13.94   
XLE                         S&P Energy          0.0286      53.31       4.95   

            5Y_return  10Y_return  
etf_ticker                         
XLK             30.82       23.07  
XLY             21.58       19.58  
XLV             17.28       16.95  
SPY             18.36       16.45  
XLF             13.15       16.15  
XLI             13.28       14.34  
XLB             15.02       12.77  
XLRE            14.61       12.56  
XLP             11.31       11.99  
XLC              8.69       11.16  
XLU             11.49       10.82  
XLE             -1.29        1.34

In [ ]:
#suppose you want select ETFs with 1Y_return < 10%

In [ ]:
sectors['1Y_return'] < 20

etf_ticker
XLK     False
XLY     False
XLV     False
SPY     False
XLF     False
XLI     False
XLB     False
XLRE    False
XLP      True
XLC      True
XLU      True
XLE     False
Name: 1Y_return, dtype: bool

In [ ]:
cond= sectors['1Y_return'] < 20
print (cond)

etf_ticker
XLK     False
XLY     False
XLV     False
SPY     False
XLF     False
XLI     False
XLB     False
XLRE    False
XLP      True
XLC      True
XLU      True
XLE     False
Name: 1Y_return, dtype: bool


In [ ]:
sectors[cond]

sector  recent_weight  1Y_return  3Y_return  \
etf_ticker                                                                     
XLP               S&P Consumer Staples          0.1200      17.20      18.05   
XLC         S&P Communication Services          0.1114      15.96      24.47   
XLU                      S&P Utilities          0.0245      16.81      13.94   

            5Y_return  10Y_return  
etf_ticker                         
XLP             11.31       11.99  
XLC              8.69       11.16  
XLU             11.49       10.82

In [ ]:
#What if we select ETFs with 1Y_return > 20 and 1Y_return < 40

In [ ]:
import numpy as np
condition= np.logical_and(sectors['1Y_return'] > 20, sectors['1Y_return'] < 40)
condition

etf_ticker
XLK      True
XLY      True
XLV      True
SPY      True
XLF      True
XLI      True
XLB      True
XLRE    False
XLP     False
XLC     False
XLU     False
XLE     False
Name: 1Y_return, dtype: bool

In [ ]:
sectors[condition]

sector  recent_weight  1Y_return  3Y_return  \
etf_ticker                                                                     
XLK         S&P Information Technology          0.2422      34.83      42.63   
XLY         S&P Consumer Discretionary          0.0632      27.93      28.65   
XLV                     S&P Healthcare          0.1309      25.59      19.69   
SPY                 US Large Cap Blend          1.0000      28.74      25.99   
XLF                     S&P Financials          0.1423      34.82      20.46   
XLI                    S&P Industrials          0.0886      21.09      20.15   
XLB                      S&P Materials          0.0227      27.45      24.00   

            5Y_return  10Y_return  
etf_ticker                         
XLK             30.82       23.07  
XLY             21.58       19.58  
XLV             17.28       16.95  
SPY             18.36       16.45  
XLF             13.15       16.15  
XLI             13.28       14.34  
XLB             15.02       12.77

In [ ]:
#4. Loops

#4.1 While loop
#The if-elif-else construct, a way to alter the flow of your scripts. As soon as Python encounters an if statement, it checks the condition.

#When this condition is True, the corresponding code is executed. If the conditions evaluates to False, and if there are elif and else statements, Python continues the search. Anyways, Python goes through this piece of code only once. After that, Python heads over to the next command in the script.

#The while loop is somewhat similar to an if statement: it executes the code inside if the condition is True. However, as opposed to the if statement, the while loop will continue to execute this code over and over again as long as the condition is true.

#The syntax of a while loop is very similar to the if statement, The while loop is not that common, but in some cases it can be very useful. When formulate a problem as 'repeating an action until a particular condition is met', a while loop is often the way to go.

#Example

In [ ]:
error = 90
i = 1
while error > 1:
    i=i+1
    error = error/3
    print (i , error)

2 30.0
3 10.0
4 3.3333333333333335
5 1.1111111111111112
6 0.3703703703703704


In [ ]:
#another example
div= 2
r = 0.1
price=0
i=0
while i < 10:
    i=i+1
    pv_div= div/(1+r)**i
    price= price + pv_div
    print('i=', 'pv_div=',i,round(pv_div,6), 'price=' ,round(price,6 ) )
print('i=', 'pv_div=',i,round(pv_div,6), 'price=' ,round(price,6 ) ) 

i= pv_div= 1 1.818182 price= 1.818182
i= pv_div= 2 1.652893 price= 3.471074
i= pv_div= 3 1.50263 price= 4.973704
i= pv_div= 4 1.366027 price= 6.339731
i= pv_div= 5 1.241843 price= 7.581574
i= pv_div= 6 1.128948 price= 8.710521
i= pv_div= 7 1.026316 price= 9.736838
i= pv_div= 8 0.933015 price= 10.669852
i= pv_div= 9 0.848195 price= 11.518048
i= pv_div= 10 0.771087 price= 12.289134
i= pv_div= 10 0.771087 price= 12.289134


In [ ]:
div= 2
r = 0.1
price=0
i=0
while i < 100:
    i=i+1
    pv_div= div/(1+r)**i
    price= price + pv_div
print('i=', 'pv_div=',round(pv_div,6), 'price=' ,round(price,6 ) ) 


i= pv_div= 0.000145 price= 19.998549


In [ ]:
div= 2
r = 0.1
price=0
i=0
while i < 1000:
    i=i+1
    pv_div= div/(1+r)**i
    price= price + pv_div
print('i=', 'pv_div=',round(pv_div,10), 'price=' ,round(price,6 ) )

i= pv_div= 0.0 price= 20.0


In [ ]:
## Price formula for preferred dividend stock is = d/r

In [ ]:
div/r

20.0

In [ ]:
#4.2 The for loop
#Syntax

In [ ]:
#for var in seq:
#    expression

In [ ]:
## example
etfs = [ "XLK ", "XLY", "XLV","SPY","XLF"]
for etf in etfs:
    print(etf)
    

XLK 
XLY
XLV
SPY
XLF


In [ ]:
div= 2
r = 0.1
price=0
i=0
for i in range(1,1000):
    pv_div= div/(1+r)**i
    price= price + pv_div
print('i=', 'pv_div=',i, round(pv_div,10), 'price=' ,round(price,6 ) ) 

i= pv_div= 999 0.0 price= 20.0


In [ ]:
#apply to strings
name = 'morningstar'
for letter in name:
    print(letter.capitalize())

M
O
R
N
I
N
G
S
T
A
R


In [ ]:
#4.3 loop over dictionary
#Consider this dictionary

In [ ]:
etf_whts ={'XLK': 0.2422, 'XLY': 0.0632, 'XLV': 0.1309, 'XLF': 0.1423, 'XLI': 0.0886, 'XLB': 0.0227, 'XLRE': 0.0257, 'XLP': 0.12, 'XLC': 0.1114, 'XLU': 0.0245, 'XLE': 0.0286} 

In [ ]:
for key,value in etf_whts:
    print(key, ';' , value)

ValueError: too many values to unpack (expected 2)

In [ ]:
#we get an error. Here is how we do it for ditionaries

In [ ]:
for key,value in etf_whts.items():
    print(key, ';' , value)

XLK ; 0.2422
XLY ; 0.0632
XLV ; 0.1309
XLF ; 0.1423
XLI ; 0.0886
XLB ; 0.0227
XLRE ; 0.0257
XLP ; 0.12
XLC ; 0.1114
XLU ; 0.0245
XLE ; 0.0286


In [ ]:
#4.4 loop on arrays

In [ ]:
import numpy as np
A = np.array([[23.07,19.58,16.95],[0.2422,0.0632,0.1309] ] )
A


array([[23.07  , 19.58  , 16.95  ],
       [ 0.2422,  0.0632,  0.1309]])

In [ ]:
for a in A:
    print(a)
#You get the whole array. 


[23.07 19.58 16.95]
[0.2422 0.0632 0.1309]


In [ ]:
#If you want to print each term separately, you do this
for a in np.nditer(A):
    print(a)

23.07
19.58
16.95
0.2422
0.0632
0.1309


In [ ]:
#4.5 Iterate over data frames

In [ ]:
#let us start with the Data frame from last week


In [ ]:
import pandas as pd
sectors= pd.read_csv('dataFiles/sector_weights_returns.csv', index_col=1) 
sectors

sector  recent_weight  1Y_return  3Y_return  \
etf_ticker                                                                     
XLK         S&P Information Technology          0.2422      34.83      42.63   
XLY         S&P Consumer Discretionary          0.0632      27.93      28.65   
XLV                     S&P Healthcare          0.1309      25.59      19.69   
SPY                 US Large Cap Blend          1.0000      28.74      25.99   
XLF                     S&P Financials          0.1423      34.82      20.46   
XLI                    S&P Industrials          0.0886      21.09      20.15   
XLB                      S&P Materials          0.0227      27.45      24.00   
XLRE                   S&P Real Estate          0.0257      45.26      22.31   
XLP               S&P Consumer Staples          0.1200      17.20      18.05   
XLC         S&P Communication Services          0.1114      15.96      24.47   
XLU                      S&P Utilities          0.0245      16.81      13.94   
XLE                         S&P Energy          0.0286      53.31       4.95   

            5Y_return  10Y_return  
etf_ticker                         
XLK             30.82       23.07  
XLY             21.58       19.58  
XLV             17.28       16.95  
SPY             18.36       16.45  
XLF             13.15       16.15  
XLI             13.28       14.34  
XLB             15.02       12.77  
XLRE            14.61       12.56  
XLP             11.31       11.99  
XLC              8.69       11.16  
XLU             11.49       10.82  
XLE             -1.29        1.34

In [ ]:
for a in sectors:
    print(a)
#we got only column names

sector
recent_weight
1Y_return
3Y_return
5Y_return
10Y_return


In [ ]:
for etf_ticker, row in sectors.iterrows():
    print(row)

sector           S&P Information Technology 
recent_weight                         0.2422
1Y_return                              34.83
3Y_return                              42.63
5Y_return                              30.82
10Y_return                             23.07
Name: XLK, dtype: object
sector           S&P Consumer Discretionary 
recent_weight                         0.0632
1Y_return                              27.93
3Y_return                              28.65
5Y_return                              21.58
10Y_return                             19.58
Name: XLY, dtype: object
sector           S&P Healthcare 
recent_weight             0.1309
1Y_return                  25.59
3Y_return                  19.69
5Y_return                  17.28
10Y_return                 16.95
Name: XLV, dtype: object
sector           US Large Cap Blend 
recent_weight                    1.0
1Y_return                      28.74
3Y_return                      25.99
5Y_return                      18.36
10

In [ ]:
#5. Random numbers
#consider a stock with a price=100
#every trading day the stock may go up with probability 0.6 and down with probability 0.4

#you have a call option to buy the stock at a price of 110. 
#The option expires at trading day 62 (3-months trading days).
#At texpiration day ( day 62) the stock price can be above 110 or below 110
#if its more than 110, say 120, you call exercise the option and make 10 dollars profit. If the price on day 62 is less than 100, say 90, your options expires worthless
#How much is this option worth to you?

#One approach is derive this value analytically. You will study this in your options class
#Another approach is to simulate the process many times, and each time the option will have a positive value or expire with zero valy, depending whether the simulated process ends up with a price more than 110 or less than 110.

#This approach is called Hacker Approach
#we can generate a random number between 0 and 1. For this we need to imports numpy. inside numpy, there is the random package.
#Inside that package we find the "rand" function.

In [ ]:
import numpy as np
np.random.rand()


0.5513147690828912

In [ ]:
#This generates a number between (0,1). 
#Run the stament again and you get another random number
#How was the random number created? 
#Computers typically generate so-called pseudo-random numbers.
#Those are random numbers that are generated using a mathematical formula, starting from a random seed. In the above case, this seed was chosen by Python when we called the rand function.
#We can also set this manually. Suppose we set it to 123. Let us call the rand function twice.

In [ ]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [ ]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [ ]:
np.random.seed(123)
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

In [ ]:
#once the seed is fixed, the sequence of the randome numbers is determine by the seed
#One advantage of this is that other people can reproduce our analysis. 
#Let's use this randomness in a new example now.


In [68]:
move=0.5
price = 100
for n in range(1,62):
    u = np.random.rand()
    if u > 0.4:
        price += move;
    else:
        price -= move
if price >= 110:
    option_excersize_value = price-110
else:option_excersize_value = 0

print('option_excersize_value=', option_excersize_value)

option_excersize_value= 1.5


In [ ]:
## Each time you run the code you get different excercise value

In [ ]:
#To assess the excersize value, we can repeat running the process a large numbe of time,
# say 100, 500, 1000. Then we calculate the average excercise value.
#Check this code

In [84]:
N=100
values_100 = []
for n in range(N):
    sum=0
    move=0.5
    price = 100
    for i in range(1,62):
        u = np.random.rand()
        if u > 0.4:
            price += move
        else:
            price -= move
    if price >= 110:
        option_excersize_value = price-110
    else:
        option_excersize_value = 0
    #print(n, 'option_excersize_value=', option_excersize_value)    
    values_100.append(option_excersize_value)
print(values_100) 

[0, 0, 0, 0, 0.5, 0, 0, 0, 0, 4.5, 0.5, 0, 0, 0, 0, 2.5, 0, 0, 2.5, 0, 0, 0, 0, 0, 0, 0, 3.5, 0, 0, 0, 0, 3.5, 0, 0, 0, 0, 0, 0, 0, 0, 4.5, 0, 0, 0, 2.5, 0, 1.5, 0, 0, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2.5, 0, 0, 0, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.5, 0, 0, 0, 4.5, 2.5, 0.5, 0, 0, 2.5, 0, 0.5, 0, 0, 0, 0, 0.5, 0, 0, 0]


In [85]:
from numpy import mean
mean_100 = mean(values_100)
round( mean_100, 2)

np.float64(0.46)

In [86]:
N= 500
values_500 = []
for n in range(N):
    sum=0
    move=0.5
    price = 100
    for i in range(1,62):
        u = np.random.rand()
        if u > 0.4:
            price += move
        else:
            price -= move
    if price >= 110:
        option_excersize_value = price-110
    else:
        option_excersize_value = 0
    #print(n, 'option_excersize_value=', option_excersize_value)    
    values_500.append(option_excersize_value)
mean_500 = mean(values_500)
print(round(mean_500, 2))

0.28


In [102]:
N= 1000
values_1000 = []
for n in range(N):
    sum=0
    move=0.5
    price = 100
    for i in range(1,62):
        u = np.random.rand()
        if u > 0.4:
            price += move
        else:
            price -= move
    if price >= 110:
        option_excersize_value = price-110
    else:
        option_excersize_value = 0
    #print(n, 'option_excersize_value=', option_excersize_value)    
    values_1000.append(option_excersize_value)
mean_1000 = mean(values_1000)
print(round(mean_1000, 2))

0.27


In [ ]:
N= 1000000
values_1000000 = []
for n in range(N):
    sum=0
    move=0.5
    price = 100
    for i in range(1,62):
        u = np.random.rand()
        if u > 0.4:
            price += move
        else:
            price -= move
    if price >= 110:
        option_excersize_value = price - 110
    else:
        option_excersize_value = 0
    #print(n, 'option_excersize_value=', option_excersize_value)    
    values_1000000.append(option_excersize_value)
mean_1000000 = mean(values_1000000)
print(round( mean_1000000, 2))

0.3


In [91]:
print ('mean_100 = ' ,round( mean_100, 2) )
print ('mean_1000 = ' ,round( mean_1000, 2) )
print ('mean_1000000 = ' ,round( mean_1000000, 2) )


mean_100 =  0.46
mean_1000 =  0.32
mean_1000000 =  0.3


In [98]:
x= np.random.uniform(0,1)
y= np.random.uniform(0,1)
if x**2+y**2 <=1:
    print(x,y, 'In the circle')
else:
    print (x,y,'out-the circle')


0.27378734750600553 0.0683068374720599 In the circle


In [101]:
N= 1000
k=0
for n in range(N):
    x= np.random.uniform(0,1)
    y= np.random.uniform(0,1)
    if x**2+y**2 <=1:
        k += 1
pi = 4 * (k/N)
print(pi)


3.064
